services:

  postgres:
    image: postgres:16-alpine
    container_name: reachinbox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox_dev_password
      POSTGRES_DB: reachinbox
    ports:
      - "5432:5432"
    volumes:
      - reachinbox_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: reachinbox-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - reachinbox_redis_data:/data

volumes:
  reachinbox_postgres_data:
  reachinbox_redis_data: